// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: rpc/user/v1/user.proto

package user_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEchoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// FIXME 请求字段必须写注释
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UserEchoReq) Reset() {
	*x = UserEchoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_user_v1_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEchoReq) ProtoMessage() {}

func (x *UserEchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_v1_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEchoReq.ProtoReflect.Descriptor instead.
func (*UserEchoReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserEchoReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserEchoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// FIXME 响应字段必须写注释
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UserEchoResp) Reset() {
	*x = UserEchoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_user_v1_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEchoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEchoResp) ProtoMessage() {}

func (x *UserEchoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_v1_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEchoResp.ProtoReflect.Descriptor instead.
func (*UserEchoResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserEchoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_user_v1_user_proto protoreflect.FileDescriptor

var file_rpc_user_v1_user_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x22, 0x1f, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x20, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x32, 0x3b, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x04,
	0x45, 0x63, 0x68, 0x6f, 0x12, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_user_v1_user_proto_rawDescOnce sync.Once
	file_rpc_user_v1_user_proto_rawDescData = file_rpc_user_v1_user_proto_rawDesc
)

func file_rpc_user_v1_user_proto_rawDescGZIP() []byte {
	file_rpc_user_v1_user_proto_rawDescOnce.Do(func() {
		file_rpc_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_user_v1_user_proto_rawDescData)
	})
	return file_rpc_user_v1_user_proto_rawDescData
}

var file_rpc_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_user_v1_user_proto_goTypes = []interface{}{
	(*UserEchoReq)(nil),  // 0: user.v1.UserEchoReq
	(*UserEchoResp)(nil), // 1: user.v1.UserEchoResp
}
var file_rpc_user_v1_user_proto_depIdxs = []int32{
	0, // 0: user.v1.User.Echo:input_type -> user.v1.UserEchoReq
	1, // 1: user.v1.User.Echo:output_type -> user.v1.UserEchoResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_user_v1_user_proto_init() }
func file_rpc_user_v1_user_proto_init() {
	if File_rpc_user_v1_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_user_v1_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEchoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_user_v1_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEchoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_user_v1_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_user_v1_user_proto_goTypes,
		DependencyIndexes: file_rpc_user_v1_user_proto_depIdxs,
		MessageInfos:      file_rpc_user_v1_user_proto_msgTypes,
	}.Build()
	File_rpc_user_v1_user_proto = out.File
	file_rpc_user_v1_user_proto_rawDesc = nil
	file_rpc_user_v1_user_proto_goTypes = nil
	file_rpc_user_v1_user_proto_depIdxs = nil
}
