// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"moocss.com/gaea/internal/biz"
	"moocss.com/gaea/internal/data"
	"moocss.com/gaea/internal/service"
	"moocss.com/gaea/pkg/log"
)

// Injectors from wire.go:

func InitApp(logger log.Logger) (*service.Services, error) {
	helloworldServer := service.NewHelloworldServer()
	dataData, err := data.NewData(logger)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo)
	userServer := service.NewUserServer(userUsecase, logger)
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	blogServer := service.NewBlogServer(articleUsecase, logger)
	services := &service.Services{
		HelloworldServer: helloworldServer,
		UserServer:       userServer,
		BlogServer:       blogServer,
	}
	return services, nil
}
